@echo off
echo Running performance tests...

mkdir reports 2>nul

echo Running auth test...
k6 run tests/k6/auth.test.js --out json=reports/auth-results1.json
if %errorlevel% neq 0 echo Auth test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running subjects test...
k6 run tests/k6/subjects.test.js --out json=reports/subjects-results1.json
if %errorlevel% neq 0 echo Subjects test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running variants test...
k6 run tests/k6/variants.test.js --out json=reports/variants-results1.json
if %errorlevel% neq 0 echo Variants test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running resources test...
k6 run tests/k6/resources.test.js --out json=reports/resources-results1.json
if %errorlevel% neq 0 echo Resources test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running subscriptions test...
k6 run tests/k6/subscriptions.test.js --out json=reports/subscriptions-results1.json
if %errorlevel% neq 0 echo Subscriptions test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running evaluations test...
k6 run tests/k6/evaluations.test.js --out json=reports/evaluations-results1.json
if %errorlevel% neq 0 echo Evaluations test failed but continuing...

timeout /t 2 /nobreak >nul

echo Running userVariants test...
k6 run tests/k6/userVariants.test.js --out json=reports/userVariants-results1.json
if %errorlevel% neq 0 echo UserVariants test failed but continuing...

echo All performance tests completed!